name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run-notebook:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install jupyter mlflow pyngrok catboost xgboost shap scikit-learn pandas numpy matplotlib

      - name: Run Notebook
        run: |
          jupyter nbconvert --to notebook --execute Data_Transformation_and_Model_Training.ipynb --output executed.ipynb
        env:
          NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}

      - name: Upload Executed Notebook Artifact
        uses: actions/upload-artifact@v2
        with:
          name: executed-notebook
          path: executed.ipynb
